server:
  port: 8100
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    active: dev
  datasource:
    url: ${DATASOURCE_HOST:jdbc:postgresql://10.0.12.48:5432/dbsilverD}
    username: ${DATASOURCE_USERNAME:silverDc_app}
    password: ${DATASOURCE_PASSWORD:24s!bCWJ$l}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

prf:
  seguranca:
    sigla-sistema: silvern
    ambiente: Homologacaobrasilia
    ip: 0.0.0.0
    token:
      secret-key: sxKY7nQWVNpcRBkt
      expire-length: 3600000
  matricula: ${MOTORCONSULTA_MATRICULA:1818002}
  cpf: ${MOTORCONSULTA_CPF:99387638120}
  barramento:
    url: ${BARRAMENTO_URL:http://barramentoprod.prf/DPRFWS}
  motor-consulta:
    url: ${MOTORCONSULTA_URL:http://motorprod1.producao1.datacenter1:8080/MotorConsultas/consulta}
  e-mail:
    hostname: smtp.prf.gov.br
    porta: 587
    timeout: 99999
    remetente: sistemasilver@prf.gov.br
    username: sistemasilver
    password: ejzlmZu6            

# logging.level:
#  root: WARN
#  org.apache.http: WARN
#  org.springframework.security: WARN
##  org.hibernate: DEBUG
##  com.zaxxer.hikari: DEBUG